export default {
  login: () => import('../views/login.vue'),
  home: () => import('../views/home.vue'),
  userAnalyze: () => import('../views/statistics/userAnalyze.vue'),
  orderAnalyze: () => import('../views/statistics/orderAnalyze.vue'),
  clientManage: () => import('../views/userManage/clientManage.vue'),
  orderManage: () => import('../views/orderManage/orderManage.vue'),
  cardManage: () => import('../views/cardManage/cardManage.vue'),
  commodityManage: () => import('../views/commodityManage/manageCommodity/commodityManage.vue'),
  activityManage: () => import('../views/userManage/activityManage/activityManage.vue'),
  sortManage: () => import('../views/commodityManage/sortManage/sortManage.vue'),
  sortManageAdd: () => import('../views/commodityManage/sortManage/sortManageAdd.vue'),
  sortManageUpdate: () => import('../views/commodityManage/sortManage/update-mixins.js'),
  account: () => import('../views/options/account/account.vue'),
  accountAdd: () => import('../views/options/account/accountAdd.vue'),
  accountUpdate: () => import('../views/options/account/accountUpdate.vue'),
  permissionAdd: () => import('../views/options/permission/permissionAdd.vue'),
  permissionUpdate: () => import('../views/options/permission/permissionUpdate.vue'),
  permission: () => import('../views/options/permission/permission.vue'),
  orderManageInfo: () => import('../views/orderManage/orderInfo.vue'),
  addCommodity: () => import('../views/commodityManage/manageCommodity/addCommodity.vue'),
  editCommodity: () => import('../views/commodityManage/manageCommodity/edit-mixins.js'),
  addActivity: () => import('../views/userManage/activityManage/addActivity.vue'),
  updateActivity: () => import('../views/userManage/activityManage/update-mixins.js'),
  newCardCustomer: () => import('../views/cardManage/addNewCard.vue')
}
